apiVersion: v2
name: devxp-app
description: Helm Charts for default DevXP-Tech Application
icon: https://github.com/devxp-tech/helm-charts/blob/main/charts/tooling/helm-icon.png
type: application
version: 0.1.72
appVersion: 1.0.0
maintainers:
  - name: diegoluisi
    email: contato@diegoluisi.eti.br