apiVersion: v2
name: tooling
description: Helm Charts to Bootstrap Kubernetes Cluster
icon: https://github.com/devxp-tech/helm-charts/blob/main/charts/tooling/helm-icon.png
type: application
version: 0.1.27
appVersion: 1.1.0
maintainers:
  - name: diegoluisi
    email: contato@diegoluisi.eti.br
