{{- if .Values.istiod.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-{{ .Values.global.application.cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.istiod.namespace }}
    server: {{ .Values.global.application.cluster.server }}
  project: {{ .Values.global.application.project }}
  source:
    chart: istiod
    helm:
      valueFiles:
      - values.yaml
      {{- with .Values.istiod.values }}
      values: |-
      {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.14.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}