{{- if .Values.sealedSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-{{ .Values.global.application.cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.sealedSecrets.namespace }}
    server: {{ .Values.global.application.cluster.server }}
  project: {{ .Values.global.application.project }}
  source:
    chart: sealed-secrets
    helm:
      valueFiles:
      - values.yaml
      {{- with .Values.sealedSecrets.values }}
      values: |-
      {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.0.10
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}